spring:
  rabbitmq:
    host: 192.168.0.100
    username: root
    virtual-host: /
    password: root
  application:
    name: mq-provider
mq:
  config:
    exchange: test.exchange
    exchange1: test1.exchange

server:
  port: 8088
